### ISSUE TITLE
[Bug] SBAS pair count doesn't update when changing filter values

### ISSUE THREAD

**Issue by asjohnston-asf** [asfadmin/Discovery-SearchUI#1843]
When performing an SBAS search, the "NN Pairs" count at the top of the left hand panel does not update as the SBAS filter criteria (date range, temporal baseline, perpendicular baseline, etc.) are adjusted.

For example, when reviewing SBAS results for `S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8`, the search initially reports 503 pairs (as of this writing). Increasing the temporal baseline filter increases the number of pairs in the list and the number of pairs ready to be submitted for On Demand processing, but the summary count does not update.

![Screenshot from 2024-01-23 10-52-32](https://github.com/asfadmin/Discovery-SearchUI/assets/17994518/7acee8e2-8b19-439a-8eed-0c48d884e7a1)
![Screenshot from 2024-01-23 10-52-40](https://github.com/asfadmin/Discovery-SearchUI/assets/17994518/fa0dc55e-cd0d-48f9-ab4e-aa4981f53f27)
![Screenshot from 2024-01-23 10-52-52](https://github.com/asfadmin/Discovery-SearchUI/assets/17994518/647f2fe8-1a10-4907-b23c-d9f842e1034b)

**Comment by williamh890** [comment]
This got fixed in v2.5.5
