### ISSUE TITLE
[Bug] Extra colon after "Type" label in On Demand Files panel

### ISSUE THREAD

**Issue by asjohnston-asf** [asfadmin/Discovery-SearchUI#1846]
There's a redundant colon after the "Type" label in the On Demand Files panel. It appears when using either the English and Spanish language setting.

![Screenshot from 2024-01-29 10-04-56](https://github.com/asfadmin/Discovery-SearchUI/assets/17994518/3ece191d-027e-4208-8eff-04e4a38cd12a)
![Screenshot from 2024-01-29 10-05-13](https://github.com/asfadmin/Discovery-SearchUI/assets/17994518/db5568cd-32f3-4520-8843-e6e46f8d1a78)

Likely caused by the i18n values including a colon for the `TYPE` field:
- https://github.com/asfadmin/Discovery-SearchUI/blob/test/src/assets/i18n/de.json#L788
- https://github.com/asfadmin/Discovery-SearchUI/blob/test/src/assets/i18n/en.json#L797
- https://github.com/asfadmin/Discovery-SearchUI/blob/test/src/assets/i18n/es.json#L797

I'm not sure if the `TYPE` field is used elsewhere, though, and it's tough to search for where that field is used, so I'll defer to the team for a fix.

**Comment by williamh890** [comment]
Fixed in v2.5.4
