### ISSUE TITLE
[Bug] Unable to submit RTC_GAMMA on demand jobs for single-polarization GRDH products 

### ISSUE THREAD

**Issue by asjohnston-asf** [asfadmin/Discovery-SearchUI#1981]
HyP3 can process RTC_GAMMA jobs for both single-polarization and dual-polarization GRDH scenes, but Vertex does not allow such jobs to be submitted for single-pol scenes.

For example, scene `S1A_IW_GRDH_1SSV_20240914T083404_20240914T083438_055658_06CBC6_6165` can be processed via the HyP3 API or SDK, example job at https://hyp3-api.asf.alaska.edu/jobs/bd00b88e-1dbe-4326-8b75-492c2ab24c12

But the "submit to HyP3" button doesn't appear for this granule (or any GRD_HS products) in Vertex:

https://search.asf.alaska.edu/#/?zoom=4.551&center=151.392,-34.900&searchType=List%20Search&maxResults=250&searchList=S1A_IW_GRDH_1SSV_20240914T083404_20240914T083438_055658_06CBC6_6165&resultsLoaded=true&granule=S1A_IW_GRDH_1SSV_20240914T083404_20240914T083438_055658_06CBC6_6165-GRD_HS
![Screenshot from 2024-09-18 19-42-25](https://github.com/user-attachments/assets/096d2052-1f12-42ca-a0ac-92008a4317e4)

I suspect this could be corrected by adding GRD_HS to the list of valid product types for RTC_GAMMA jobs at https://github.com/asfadmin/Discovery-SearchUI/blob/test/src/app/models/hyp3-jobs.model.ts#L15

**Comment by SpicyGarlicAlbacoreRoll** [comment]
Fixed with the latest release
